### ISSUE TITLE
Extension blocks left column of Facebook, in addition to newsfeed

### ISSUE THREAD

**Issue by tanderson92** [yczeng/hackernews-newsfeed#4]
It would be nice to not have the left column blocked, which contains many useful shortcuts to parts of facebook having nothing to do with the newsfeed. The tampermonkey version of this idea implements this functionality and only replaces the center column.

**Comment by hoppermori** [comment]
Hi @tanderson92,

When I originally wrote the extension for myself, I wanted all of my Facebook newsfeed gone and I continue to want this feature.

The tampermonkey version was the result of a pull request from @apizzimenti who implemented this for Firefox independently.

However, @dpfrakes was nice enough to make what you are requesting and I suggest that you just use his version for chrome. See https://github.com/dpfrakes/hackernews-newsfeed. Note that I haven't tested his extension yet, so use it at your own discretion.

Thanks,
Catherine
