### ISSUE TITLE
As a fb user I want to pause extension time to time 

### ISSUE THREAD

**Issue by charithsoori** [yczeng/hackernews-newsfeed#7]

**Comment by apizzimenti** [comment]
Could you give us a few more details about what you'd like to see implemented to achieve this?

**Comment by hoppermori** [comment]
Hi @charithsoori,

Thank you for your feedback! The point of the extension is to prevent you from using Facebook, so allowing users to pause it wouldn't make any sense.

Thanks,
Catherine

**Comment by charithsoori** [comment]
Thanks . Objective is clear
